### ISSUE TITLE
Debian 10, kernel 4.19.0-18, implicit declaration of function ‘ref_module’; did you mean ‘use_module’

### ISSUE THREAD

**Issue by streamthing** [aabc/ipt-netflow#190]
I can't compile from apt with dkms on `4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29)`
same issue as https://github.com/aabc/ipt-netflow/issues/177
Could you help me?

```
Loading new ipt-netflow-2.3 DKMS files...
Building for 4.19.0-18-amd64
Building initial module for 4.19.0-18-amd64
Error! Bad return status for module build on kernel: 4.19.0-18-amd64 (x86_64)
Consult /var/lib/dkms/ipt-netflow/2.3/build/make.log for more information.
```

```  CC [M]  /var/lib/dkms/ipt-netflow/2.3/build/ipt_NETFLOW.o
/var/lib/dkms/ipt-netflow/2.3/build/ipt_NETFLOW.c: In function ‘nf_seq_show’:
/var/lib/dkms/ipt-netflow/2.3/build/ipt_NETFLOW.c:749:39: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘s64’ {aka ‘long long int’} [-Wformat=]
    seq_printf(seq, " Flows selected %lu, discarded %lu.",
                                     ~~^
                                     %llu
        atomic64_read(&flows_selected),
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/ipt-netflow/2.3/build/ipt_NETFLOW.c:749:54: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘s64’ {aka ‘long long int’} [-Wformat=]
    seq_printf(seq, " Flows selected %lu, discarded %lu.",
                                                    ~~^
                                                    %llu
/var/lib/dkms/ipt-netflow/2.3/build/ipt_NETFLOW.c:751:8:
        atomic64_read(&flows_observed) - atomic64_read(&flows_selected));
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/ipt-netflow/2.3/build/ipt_NETFLOW.c:753:39: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘s64’ {aka ‘long long int’} [-Wformat=]
    seq_printf(seq, " Flows selected %lu.", atomic64_read(&flows_selected));
                                     ~~^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                     %llu
In file included from /var/lib/dkms/ipt-netflow/2.3/build/ipt_NETFLOW.c:75:
/var/lib/dkms/ipt-netflow/2.3/build/ipt_NETFLOW.c: In function ‘register_ct_events’:
/var/lib/dkms/ipt-netflow/2.3/build/compat.h:173:21: error: implicit declaration of function ‘ref_module’; did you mean ‘use_module’? [-Werror=implicit-function-declaration]
 # define use_module ref_module
                     ^~~~~~~~~~
/var/lib/dkms/ipt-netflow/2.3/build/ipt_NETFLOW.c:5399:3: note: in expansion of macro ‘use_module’
   use_module(THIS_MODULE, netlink_m);
   ^~~~~~~~~~
cc1: some warnings being treated as errors
```

**Comment by streamthing** [comment]
But works on 4.19.0-14-amd64

**Comment by xtaran** [comment]
This is not an upstream issue but a Debian package issue. See https://bugs.debian.org/990123.

If you are able to build Debian packages yourself, please try the package in the `buster` branch in https://salsa.debian.org/debian/iptables-netflow/-/commits/buster as mentioned in https://bugs.debian.org/990739

**Comment by xtaran** [comment]
I asked the Debian release team in July for the OK to go forward with the fix for buster, but only got a reply in December — which I admittedly noticed only very recently. See https://bugs.debian.org/990739 for the history and of and to follow the buster update.

**Comment by xtaran** [comment]
@aabc: Feel free to add me as Assignee for this issue.

**Comment by streamthing** [comment]
buster doesn't have version newer than 2.3-5 :(
https://packages.debian.org/buster/iptables-netflow-dkms

**Comment by xtaran** [comment]
> buster doesn't have version newer than 2.3-5 :( https://packages.debian.org/buster/iptables-netflow-dkms

That's my point. That's why I wrote "If you are able to build Debian packages yourself".

**Comment by streamthing** [comment]
@xtaran Could you send fixed package to Debian? Or send information to Debian about update.

**Comment by streamthing** [comment]
Any updates?
