### ISSUE TITLE
ipt_netflow fail to build on kernel 5.1.2

### ISSUE THREAD

**Issue by danrimal** [aabc/ipt-netflow#115]
Hello,
At first, huge thanks for this software, i really appreciate this effort.
Now, i am trying to build ipt_netflow on centos 7 with elrepo kernel-ml, ie latest is:
5.1.2-1.el7.elrepo.x86_64

Build fails with:

```
Compiling for kernel 5.1.2-1.el7.elrepo.x86_64
make -C /lib/modules/5.1.2-1.el7.elrepo.x86_64/build M=/root/ipt-netflow modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory `/usr/src/kernels/5.1.2-1.el7.elrepo.x86_64'
  CC [M]  /root/ipt-netflow/ipt_NETFLOW.o
/root/ipt-netflow/ipt_NETFLOW.c: In function ‘ipt_netflow_fini’:
/root/ipt-netflow/ipt_NETFLOW.c:5724:2: error: implicit declaration of function ‘synchronize_sched’ [-Werror=implicit-function-declaration]
  synchronize_sched();
  ^
cc1: some warnings being treated as errors
make[3]: *** [/root/ipt-netflow/ipt_NETFLOW.o] Error 1
make[2]: *** [_module_/root/ipt-netflow] Error 2
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory `/usr/src/kernels/5.1.2-1.el7.elrepo.x86_64'
make: *** [ipt_NETFLOW.ko] Error 2
```
With distro kernel (ie something about kernel 3.10) on the same machine, building works. So it looks like kernel version issue.

**Comment by aabc** [comment]
Thanks for the report. Should be fixed by now in git master.
