### ISSUE TITLE
Error in 5.15.86 ct_event

### ISSUE THREAD

**Issue by DocMAX** [aabc/ipt-netflow#209]
```
Test member nf_ct_event_notifier.ct_event net/netfilter/nf_conntrack_ecache.h  undeclared
egrep: warning: egrep is obsolescent; using grep -E
Error: unexpected error from compiler
make -s -B -C /mnt/zeus/hdd/sources/openwrt/sources/snapshot/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.15.86 M=/mnt/zeus/hdd/sources/openwrt/sources/snapshot/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/ipt-netflow-40fefb2/cc-test-build modules
/mnt/zeus/hdd/sources/openwrt/sources/snapshot/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/ipt-netflow-40fefb2/cc-test-build/test.c:4:41: error: invalid use of undefined type 'struct nf_ct_event_notifier'
    4 | typeof(((struct nf_ct_event_notifier*)0)->ct_event) test;
      |                                         ^~
make[5]: *** [scripts/Makefile.build:289: /mnt/zeus/hdd/sources/openwrt/sources/snapshot/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/ipt-netflow-40fefb2/cc-test-build/test.o] Error 1
make[4]: *** [Makefile:1903: /mnt/zeus/hdd/sources/openwrt/sources/snapshot/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/ipt-netflow-40fefb2/cc-test-build] Error 2

make[3]: *** [Makefile:30: compat_def.h] Error 3
make[3]: Leaving directory '/mnt/zeus/hdd/sources/openwrt/sources/snapshot/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/ipt-netflow-40fefb2'
make[2]: *** [Makefile:121: /mnt/zeus/hdd/sources/openwrt/sources/snapshot/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/ipt-netflow-40fefb2/.built] Error 2
make[2]: Leaving directory '/mnt/zeus/hdd/sources/openwrt/sources/snapshot/package/network/ipt-netflow'
time: package/network/ipt-netflow/compile#14.33#7.78#21.41
    ERROR: package/network/ipt-netflow failed to build.
make[1]: *** [package/Makefile:116: package/network/ipt-netflow/compile] Error 1
make[1]: Leaving directory '/mnt/zeus/hdd/sources/openwrt/sources/snapshot'
make: *** [/mnt/zeus/hdd/sources/openwrt/sources/snapshot/include/toplevel.mk:231: package/network/ipt-netflow/compile] Fehler 2
```

**Comment by svlobanov** [comment]
It might be openwrt env issue. Do you have the same issue if compile on regular host for regular host? (e.g. debian normal setup)

**Comment by kalamlacki** [comment]
ipt-netflow versions 2.6 or 2.5.1 cannot be compiled against openwrt trunk

when you change openwrt MakeFile and comment this:
#PKG_VERSION:=2.6
#PKG_SOURCE_VERSION:=v$(PKG_VERSION)

and uncomment this:

PKG_VERSION:=$(shell (git ls-remote $(PKG_SOURCE_URL) | grep refs/heads/master | cut -f 1 | head -c 7))
PKG_SOURCE_VERSION:=HEAD

then you will compile current master branch and not versions of ipt-netflow on openwrt and it will work fine.

The proof: http://kalamlacki.eu/ipt-netflow/develop_2023_01_06/

**Comment by kalamlacki** [comment]
What kind of distro were you using for compilation, which openwrt SDK you were using?
I compiled this on Ubuntu 18.04.6

**Comment by DocMAX** [comment]
Latest Arch Linux. OpenWRT cloned from https://github.com/openwrt/openwrt.git.
Target is Turris Omnia router.
I will try a make dirclean. Sometimes this helps.

**Comment by DocMAX** [comment]
i'm not sure what is this about. my procedure is
1) clone openwrt git
2) put makefile in /package/network/ipt-netflow
3) make menuconfig, select my board and software and netflow
4) compile with make -j16

is something wrong with this?

**Comment by kalamlacki** [comment]
xz -d< openwrt-sdk-mvebu-cortexa9_gcc-11.3.0_musl_eabi.Linux-x86_64.tar.xz | tar -xv
cd openwrt-sdk-mvebu-cortexa9_gcc-11.3.0_musl_eabi.Linux-x86_64
./scripts/feeds update -a
./scripts/feeds install iptables
make package/ipt-netflow/compile V=99

**Comment by kalamlacki** [comment]
It will take a few minutes to compile

**Comment by DocMAX** [comment]
what is wrong with my procedure?
what is different to openwrt-sdk-mvebu-cortexa9_gcc-11.3.0_musl_eabi.Linux-x86_64?

**Comment by kalamlacki** [comment]
if you do not compile the whole Openwrt from sources SDK is sufficient.
Is my procedure working ?

**Comment by DocMAX** [comment]
yes compiles with no issues. thanks :-) but i wonder why it's not compiling with the openwrt source.

**Comment by DocMAX** [comment]
you know what worked? i simply deleted:
./build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.15.86/include/net/netfilter/nf_conntrack_ecache.h2
./build_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.3.0_musl_eabi/linux-5.15.86/include/net/netfilter/nf_conntrack_ecache.h2

and now it comiles without errors, can someone explain??!?!?

**Comment by DocMAX** [comment]
anything i do on openwrt git snapshot i'm stuck at this "test":
@aabc please advice, thanks!
`test.c:4:41: error: invalid use of undefined type 'struct nf_ct_event_notifier'`

**Comment by DocMAX** [comment]
@kalamlacki root cause ist https://github.com/aabc/ipt-netflow/commit/6a55739a9bf9fb890dbd1aa338057f394b766ab8
i removed that test what ever it does and now it's compiling fine.
that's why it working in 2.5.1 before, because this commit is missing.
@aabc please have a look.

**Comment by kalamlacki** [comment]
@DocMAX  I saw that you did fork of ipt-netflow repository. Are you going to maintain it?
The next thing to do is PREMPTING support because modern kernels have this feature turned on and this module does not support it.

**Comment by vvfedorenko** [comment]
the definition of `struct nf_ct_event_notifier` is hidden behind CONFIG_NF_CONNTRACK_EVENTS option. If the kernel configuration doesn't have it, you will get such kind of error while running `configure --enable-nat-events`. Consider changing kernel options in your build, it's disabled by default in OpenWRT
