### ISSUE TITLE
Won't compile on 4.1.0-0.bpo.2-amd64

### ISSUE THREAD

**Issue by hotid** [aabc/ipt-netflow#44]
```
 make all
Compiling for kernel 4.1.6
make -C /lib/modules/4.1.0-0.bpo.2-amd64/build M=/root/ipt-netflow modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory '/usr/src/linux-headers-4.1.0-0.bpo.2-amd64'
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
  CC [M]  /root/ipt-netflow/ipt_NETFLOW.o
/root/ipt-netflow/ipt_NETFLOW.c: In function ‘hsize_procctl’:
/root/ipt-netflow/ipt_NETFLOW.c:1427:2: error: unknown type name ‘ctl_table_no_const’
  ctl_table_no_const lctl = *ctl;
  ^
/root/ipt-netflow/ipt_NETFLOW.c:1427:28: error: incompatible types when initializing type ‘int’ using type ‘struct ctl_table’
  ctl_table_no_const lctl = *ctl;
                            ^
/root/ipt-netflow/ipt_NETFLOW.c:1430:7: error: request for member ‘data’ in something not a structure or union
   lctl.data = &hsize;
       ^
/root/ipt-netflow/ipt_NETFLOW.c:1431:22: warning: passing argument 1 of ‘proc_dointvec’ from incompatible pointer type
  ret = proc_dointvec(&lctl, write, BEFORE2632(filp,) buffer, lenp, fpos);
                      ^
In file included from /usr/src/linux-headers-4.1.0-0.bpo.2-common/include/linux/kmod.h:27:0,
                 from /usr/src/linux-headers-4.1.0-0.bpo.2-common/include/linux/module.h:13,
                 from /root/ipt-netflow/ipt_NETFLOW.c:21:
/usr/src/linux-headers-4.1.0-0.bpo.2-common/include/linux/sysctl.h:42:12: note: expected ‘struct ctl_table *’ but argument is of type ‘int *’
 extern int proc_dointvec(struct ctl_table *, int,
            ^
/root/ipt-netflow/ipt_NETFLOW.c: In function ‘sndbuf_procctl’:
/root/ipt-netflow/ipt_NETFLOW.c:1445:2: error: unknown type name ‘ctl_table_no_const’
  ctl_table_no_const lctl = *ctl;
  ^
/root/ipt-netflow/ipt_NETFLOW.c:1445:28: error: incompatible types when initializing type ‘int’ using type ‘struct ctl_table’
  ctl_table_no_const lctl = *ctl;
                            ^
/root/ipt-netflow/ipt_NETFLOW.c:1457:6: error: request for member ‘data’ in something not a structure or union
  lctl.data = &sndbuf;
      ^
/root/ipt-netflow/ipt_NETFLOW.c:1458:22: warning: passing argument 1 of ‘proc_dointvec’ from incompatible pointer type
  ret = proc_dointvec(&lctl, write, BEFORE2632(filp,) buffer, lenp, fpos);
                      ^
In file included from /usr/src/linux-headers-4.1.0-0.bpo.2-common/include/linux/kmod.h:27:0,
                 from /usr/src/linux-headers-4.1.0-0.bpo.2-common/include/linux/module.h:13,
                 from /root/ipt-netflow/ipt_NETFLOW.c:21:
/usr/src/linux-headers-4.1.0-0.bpo.2-common/include/linux/sysctl.h:42:12: note: expected ‘struct ctl_table *’ but argument is of type ‘int *’
 extern int proc_dointvec(struct ctl_table *, int,
            ^
/root/ipt-netflow/ipt_NETFLOW.c: In function ‘flush_procctl’:
/root/ipt-netflow/ipt_NETFLOW.c:1587:2: error: unknown type name ‘ctl_table_no_const’
  ctl_table_no_const lctl = *ctl;
  ^
/root/ipt-netflow/ipt_NETFLOW.c:1587:28: error: incompatible types when initializing type ‘int’ using type ‘struct ctl_table’
  ctl_table_no_const lctl = *ctl;
                            ^
/root/ipt-netflow/ipt_NETFLOW.c:1589:6: error: request for member ‘data’ in something not a structure or union
  lctl.data = &val;
      ^
/root/ipt-netflow/ipt_NETFLOW.c:1590:22: warning: passing argument 1 of ‘proc_dointvec’ from incompatible pointer type
  ret = proc_dointvec(&lctl, write, BEFORE2632(filp,) buffer, lenp, fpos);
                      ^
In file included from /usr/src/linux-headers-4.1.0-0.bpo.2-common/include/linux/kmod.h:27:0,
                 from /usr/src/linux-headers-4.1.0-0.bpo.2-common/include/linux/module.h:13,
                 from /root/ipt-netflow/ipt_NETFLOW.c:21:
/usr/src/linux-headers-4.1.0-0.bpo.2-common/include/linux/sysctl.h:42:12: note: expected ‘struct ctl_table *’ but argument is of type ‘int *’
 extern int proc_dointvec(struct ctl_table *, int,
            ^
/root/ipt-netflow/ipt_NETFLOW.c: In function ‘protocol_procctl’:
/root/ipt-netflow/ipt_NETFLOW.c:1616:2: error: unknown type name ‘ctl_table_no_const’
  ctl_table_no_const lctl = *ctl;
  ^
/root/ipt-netflow/ipt_NETFLOW.c:1616:28: error: incompatible types when initializing type ‘int’ using type ‘struct ctl_table’
  ctl_table_no_const lctl = *ctl;
                            ^
/root/ipt-netflow/ipt_NETFLOW.c:1618:6: error: request for member ‘data’ in something not a structure or union
  lctl.data = &ver;
      ^
/root/ipt-netflow/ipt_NETFLOW.c:1619:22: warning: passing argument 1 of ‘proc_dointvec’ from incompatible pointer type
  ret = proc_dointvec(&lctl, write, BEFORE2632(filp,) buffer, lenp, fpos);
                      ^
In file included from /usr/src/linux-headers-4.1.0-0.bpo.2-common/include/linux/kmod.h:27:0,
                 from /usr/src/linux-headers-4.1.0-0.bpo.2-common/include/linux/module.h:13,
                 from /root/ipt-netflow/ipt_NETFLOW.c:21:
/usr/src/linux-headers-4.1.0-0.bpo.2-common/include/linux/sysctl.h:42:12: note: expected ‘struct ctl_table *’ but argument is of type ‘int *’
 extern int proc_dointvec(struct ctl_table *, int,
            ^
/usr/src/linux-headers-4.1.0-0.bpo.2-common/scripts/Makefile.build:269: recipe for target '/root/ipt-netflow/ipt_NETFLOW.o' failed
make[4]: *** [/root/ipt-netflow/ipt_NETFLOW.o] Error 1
/usr/src/linux-headers-4.1.0-0.bpo.2-common/Makefile:1401: recipe for target '_module_/root/ipt-netflow' failed
make[3]: *** [_module_/root/ipt-netflow] Error 2
Makefile:146: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.1.0-0.bpo.2-amd64'
Makefile:24: recipe for target 'ipt_NETFLOW.ko' failed
make: *** [ipt_NETFLOW.ko] Error 2
```

Ugly fix:
```
diff --git a/compat.h b/compat.h
index dd3cfc6..59c625b 100644
--- a/compat.h
+++ b/compat.h
@@ -77,9 +77,6 @@ union nf_inet_addr {

 # if LINUX_VERSION_CODE >= KERNEL_VERSION(3,17,0)
 #  define ctl_table struct ctl_table
-# endif
-
-# ifndef CONFIG_GRKERNSEC
 #  define ctl_table_no_const ctl_table
 # endif
 #endif
```

**Comment by aabc** [comment]
Что это за ядро и откуда оно взялось?

**Comment by aabc** [comment]
Покажите `/boot/config-4.1.0-0.bpo.2-amd64` от этого ядра, если не трудно. Получается, что в Debian-е определен символ CONFIG_GRKERNSEC из Gentoo.

**Comment by hotid** [comment]
Дебиановское из jessie-backports.
```
 cat /boot/config-4.1.0-0.bpo.2-amd64 | grep GRKERNSEC
CONFIG_GRKERNSEC=y
CONFIG_GRKERNSEC_PERF_HARDEN=y
```

**Comment by hotid** [comment]
https://packages.debian.org/jessie-backports/linux-image-4.1.0-0.bpo.2-amd64

**Comment by aabc** [comment]
Спасибо. То есть Дебиан частично влючил патч от Grsecurity, но не включил часть с ctl_table_no_const. Надо разбираться как это теперь правильно заifdefить...

**Comment by hotid** [comment]
```
diff --git a/compat.h b/compat.h
index dd3cfc6..a140ce8 100644
--- a/compat.h
+++ b/compat.h
@@ -79,7 +79,7 @@ union nf_inet_addr {
 #  define ctl_table struct ctl_table
 # endif

-# ifndef CONFIG_GRKERNSEC
+# ifndef ctl_table_no_const
 #  define ctl_table_no_const ctl_table
 # endif
 #endif
```
Не?

**Comment by aabc** [comment]
https://www.grsecurity.net/test/grsecurity-3.1-4.1.7-201509201149.patch

    typedef struct ctl_table __no_const ctl_table_no_const;

Надо смотреть что именно включил Дебиан.

**Comment by hotid** [comment]
```
  * security: Apply and enable GRKERNSEC_PERF_HARDEN feature from Grsecurity,
    disabling use of perf_event_open() by unprivileged users by default
    (sysctl: kernel.perf_event_paranoid)
```
Патчи: http://igorsd.ru/gr/

**Comment by hotid** [comment]
Судя по всему - там только GRKERNSEC_PERF_HARDEN добавили.

**Comment by aabc** [comment]
Спрашвается зачем они сделали CONFIG_GRKERNSEC, если там только GRKERNSEC_PERF_HARDEN. Вот и не понятно какой ifdef теперь делать...

**Comment by hotid** [comment]
А чем плох # ifndef ctl_table_no_const?

**Comment by aabc** [comment]
А в чём его смысл? ctl_table_no_const никогда не определен, это не define.

**Comment by aabc** [comment]
Дебиановцы безответственно поступили включив патч в таком виде, что его не отличить от реального Grsecurity. Я поискал дефайны по которым бы можно было отличить реальный Grsecurity, они есть, если делать `#include <linux/grsecurity.h>`, но чтоб его сделать надо знать, что Grsecurity есть, а как раз это и неизвестно. :disappointed:

Остаётся поискать что-нибудь чтоб отличить ядро дебиана.

**Comment by hotid** [comment]
Да, чёт не подумал.
Может так?
```
diff --git a/compat.h b/compat.h
index dd3cfc6..4a7b640 100644
--- a/compat.h
+++ b/compat.h
@@ -79,7 +79,7 @@ union nf_inet_addr {
 #  define ctl_table struct ctl_table
 # endif

-# ifndef CONFIG_GRKERNSEC
+# ifndef HAVE_GRSECURITY_H
 #  define ctl_table_no_const ctl_table
 # endif
 #endif
diff --git a/configure b/configure
index c6c5593..1278c61 100755
--- a/configure
+++ b/configure
@@ -453,6 +453,7 @@ kernel_check_include() {

 kernel_check_features() {
   kernel_check_include include/linux/llist.h -DHAVE_LLIST
+  kernel_check_include include/linux/grsecurity.h -DHAVE_GRSECURITY_H
 }

 snmp_check() {
```

**Comment by aabc** [comment]
Да, через configure нормальный вариант.
