### ISSUE TITLE
Doesn't compiles on 3.11.10

### ISSUE THREAD

**Issue by xaionaro** [aabc/ipt-netflow#2]
```
/usr/src/ipt_netflow-1.8]# make
Compiling for kernel 3.11.10
make -C /lib/modules/3.11.10/build M=/usr/src/ipt_netflow-1.8 modules
make[1]: Entering directory `/usr/src/linux-3.11.10'
  CC [M]  /usr/src/ipt_netflow-1.8/ipt_NETFLOW.o
/usr/src/ipt_netflow-1.8/ipt_NETFLOW.c: In function ‘ipt_netflow_find’:
/usr/src/ipt_netflow-1.8/ipt_NETFLOW.c:859:62: error: macro "hlist_for_each_entry" passed 4 arguments, but takes just 3
  hlist_for_each_entry(nf, pos, &ipt_netflow_hash[hash], hlist) {
                                                              ^
/usr/src/ipt_netflow-1.8/ipt_NETFLOW.c:859:2: error: ‘hlist_for_each_entry’ undeclared (first use in this function)
  hlist_for_each_entry(nf, pos, &ipt_netflow_hash[hash], hlist) {
  ^
/usr/src/ipt_netflow-1.8/ipt_NETFLOW.c:859:2: note: each undeclared identifier is reported only once for each function it appears in
/usr/src/ipt_netflow-1.8/ipt_NETFLOW.c:859:64: error: expected ‘;’ before ‘{’ token
  hlist_for_each_entry(nf, pos, &ipt_netflow_hash[hash], hlist) {
                                                                ^
/usr/src/ipt_netflow-1.8/ipt_NETFLOW.c:857:21: warning: unused variable ‘pos’ [-Wunused-variable]
  struct hlist_node *pos;
                     ^
/usr/src/ipt_netflow-1.8/ipt_NETFLOW.c:856:22: warning: unused variable ‘nf’ [-Wunused-variable]
  struct ipt_netflow *nf;
                      ^
/usr/src/ipt_netflow-1.8/ipt_NETFLOW.c: In function ‘ipt_netflow_init’:
/usr/src/ipt_netflow-1.8/ipt_NETFLOW.c:1407:17: error: ‘num_physpages’     undeclared (first use in this function)
   hashsize = (((num_physpages << PAGE_SHIFT) / 16384)
                 ^
/usr/src/ipt_netflow-1.8/ipt_NETFLOW.c:1437:2: error: implicit declaration of function ‘create_proc_entry’ [-Werror=implicit-function-declaration]
  proc_stat = create_proc_entry("ipt_netflow", S_IRUGO, INIT_NET(proc_net_stat));
  ^
/usr/src/ipt_netflow-1.8/ipt_NETFLOW.c:1437:12: warning: assignment makes pointer from integer without a cast [enabled by default]
  proc_stat = create_proc_entry("ipt_netflow", S_IRUGO, INIT_NET(proc_net_stat));
            ^
/usr/src/ipt_netflow-1.8/ipt_NETFLOW.c:1442:11: error: dereferencing pointer to incomplete type
  proc_stat->proc_fops = &nf_seq_fops;
           ^
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/ipt_netflow-1.8/ipt_NETFLOW.o] Error 1
make[1]: *** [_module_/usr/src/ipt_netflow-1.8] Error 2
make[1]: Leaving directory `/usr/src/linux-3.11.10'
make: *** [ipt_NETFLOW.ko] Error 2
```
